### ISSUE TITLE
希望能将Blur应用到控件上

### ISSUE THREAD

**Issue by ChuanShuoShuai** [TianXiaTech/BlurWindow#1]
在一些wpf右键菜单、label透明背景、窗口内全局blur中需要使用模糊增强视觉效果，会使窗口UI层次感更明显

**Comment by zhaotianff** [comment]
可以的，大兄弟 ，有空看看能不能实现。有兴趣可以一起参与。

**Comment by ChuanShuoShuai** [comment]
天呐，居然回复我了，我也是在Nuget搜了一下，就看到了你的项目🤣，调用比其他库简单一点，目前我还是小白一个

**Comment by ChuanShuoShuai** [comment]
![image](https://user-images.githubusercontent.com/94915862/187341695-46078b7a-f264-4288-89f0-11357497a166.png)
类似于这种效果

**Comment by MiraHikari** [comment]
支持了

**Comment by zhaotianff** [comment]
有时间了，安排上。issue关了

**Comment by ChuanShuoShuai** [comment]
谢谢大佬~
