### ISSUE TITLE
悲，win11 22H2没有这个模糊效果了

### ISSUE THREAD

**Issue by ChuanShuoShuai** [TianXiaTech/BlurWindow#2]
21H2及以下版本：
![cf137687926d3b2a9728262919795834198316802 png@1295w](https://user-images.githubusercontent.com/94915862/191419555-07df847b-406d-4c20-bdbb-e8b341f04edf.jpg)
22H2现在版本：
![QQ截图20220921131153](https://user-images.githubusercontent.com/94915862/191419642-2256c96f-4f9c-4169-83cc-dc26fab2a045.png)

**Comment by zhaotianff** [comment]
win11换成一种叫Mica云母的效果了，目前我还没用上win11，所以我也没详细 去了解过，哈哈。
![image](https://user-images.githubusercontent.com/22126367/192430022-870e1131-03ac-46a3-b10e-3235ea49a7fc.png)

试下这个包：
```
NuGet\Install-Package MicaWPF -Version 4.6.2
```

**Comment by liu-qingyuan** [comment]
WinBlur也行，不过不是全局半透明。是Win11 命令行半透明那种，失去焦点会变灰

**Comment by zhaotianff** [comment]
最近我自己在虚拟机里装 了Windows 11，发现在Windows 11 22H2中确实移除了这种效果，在这之前的版本是可以用的。根据网上的消息来看，微软正在开发一种新的Blur效果，到时候等新API出来，我第一时间集成到项目里来。
