### ISSUE TITLE
窗体是纯白的，并没有透明

### ISSUE THREAD

**Issue by SoyBeanMilkx** [TianXiaTech/BlurWindow#3]
按照您的写法，窗口并没有透明，还是纯白色的，可以麻烦您帮我看下嘛，我的QQ是2661293913，或者您给我一个联系方式，麻烦您了

**Comment by hupo376787** [comment]
区分系统，23h2不支持了，低版本的没试过

**Comment by zhaotianff** [comment]
是的，是系统版本的问题，你运行demo，只有纯白效果，就说明系统版本太新了。系统已经移除了这个效果。
可以使用Mica.WPF这个库替代。
