### ISSUE TITLE
Opacity is invalid

### ISSUE THREAD

**Issue by zq80** [TianXiaTech/BlurWindow#4]
Opacity set to 0.5 0.1 and 0 is no diffirent. but set to 0 you click form you will click the under form. 
vs 2022 and win11

**Comment by zhaotianff** [comment]
What is your system version number?

**Comment by zhaotianff** [comment]
I tested in Win11 22H2，it works well.

![212](https://github.com/TianXiaTech/BlurWindow/assets/22126367/ecfedc8c-f668-47d8-840f-ab748d9ce555)

**Comment by zq80** [comment]
I just try,it's ok. May be some setting is wrong last time
